import Nav from '@/components/ui/Nav'
import Provider from '@/components/ui/provider'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
    title: 'PadleHoy',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='es'>
            <body>
                <Provider>
                    <Nav />
                    {children}
                </Provider>
            </body>
        </html>
    )
}
